### ISSUE TITLE
compressing vcf file (rule remove_CpG_vcf - 8.1_vcf_CpG_filtering.smk)

### ISSUE THREAD

**Issue by ndussex** [NBISweden/GenErode#19]
Hi, 

In the '8.1_vcf_CpG_filtering.smk' file, the rule 'remove_CpG_vcf' uses bedtools intersect to generate a vcf file without CpG sites, such as:

_bedtools intersect -a {input.vcf} -b {input.bed} -header -sorted -g {input.genomefile} > {output.filtered} 2> {log}_

However, the {output.filtered} file is not compressed and thus very large, which means that a project directory can very quickly be full. 

Would it be possible to compress this vcf file to save space with something like below to generate a *vcf.gz file?

 _bedtools intersect -a {input.vcf} -b {input.bed} -header -sorted -g {input.genomefile} | bgzip -c > {output.filtered} 2> {log}_

Much appreciated,
Nic

**Comment by verku** [comment]
Hi! The bedtools container used by the pipeline does not contain bgzip, so we'll create a new Docker container with bedtools and tabix/bgzip so that it's possible to compress the file.
