### ISSUE TITLE
Singularity issue?

### ISSUE THREAD

**Issue by ndussex** [NBISweden/GenErode#30]
Hi, 

Since the last maintenance window on uppmax, I am having issues running the pipeline and got the following error:

WorkflowError:
Minimum singularity version is 2.4.1.
  File "/home/nicd/.conda/envs/generode/lib/python3.7/site-packages/snakemake/deployment/singularity.py", line 48, in __init__

I tried recreating the generode environment, as such:

conda env create -n generode -f environment.yml
conda activate generode

But I still have the same issue when launching the snakemake command.

Would you mind helping me with this please?

Thanks!

**Comment by ndussex** [comment]
Hi again,

I just asked the uppmax support about this issue and why/if they had downgraded singularity. I got the following answer:

this is something we did not expect... During the maintenance window we replaced Singularity with Apptainer i.e. singularity command starts apprtainer. They are compatible, but sure now the version reported will be 1.1.something
and the rule fails. Let me discuss this with my colleagues and see if there is a solution around for this (or we need to come with something else).

**Comment by ndussex** [comment]
Issue sorted, one needs to use the latest stable snakemake version, replace the current one with:

 - snakemake=7.18.1

in the environment.yml file recreate the generode environment.

**Comment by johnne** [comment]
Hi @ndussex,
thanks for reporting this, and for posting your solution. @verku has a pull request for upgrading the snakemake used in the pipeline so hopefully this issue will be fixed for future users as well. I'll leave the issue open until that PR is merged.

**Comment by verku** [comment]
Thanks! I'll run some final checks and will merge the PR and update the documentation thereafter.
