### ISSUE TITLE
Issues with cookiecutter in UPPMAX

### ISSUE THREAD

**Issue by jcchacond** [NBISweden/GenErode#31]
Hello,

I'm trying to set up the slurm profile with cookiecutter (using the latest version of the pipeline v0.4.2), but the options look very different to what is described in GenErode's Wiki.

This is how it looks like:

<img width="960" alt="2022-12-14" src="https://user-images.githubusercontent.com/46746773/207625640-b15bc43f-7d8c-4c5d-b62f-1f3cc06ced1e.png">

Apparently it is asking me to manually input all the configuration instead of retrieving it from the config/cluster.yaml.

I used cookiecutter earlier this year both in UPPMAX and another slurm-based cluster and it was working exactly as it is described in the Wiki. I'm not sure if the issue I'm finding now is related to recent changes in UPPMAX or in the Snakemake git profile.

Thanks in advance, I'd appreciate any suggestions on how to proceed in order to set up the Snakemake profile.

**Comment by verku** [comment]
The cookiecutter is continuously being updated and eventually the cluster.yaml file may not work with it anymore. I'll look into it and will let you know how to solve this.

**Comment by verku** [comment]
Thanks again for letting me know! The latest slurm profile is still compatible with the cluster.yaml file from the pipeline. I've updated the WIKI with how to set up the slurm profile accordingly: https://github.com/NBISweden/GenErode/wiki/2.-Requirements-&-pipeline-configuration
