### ISSUE TITLE
Rerun issue with snakemake 7.8

### ISSUE THREAD

**Issue by lored322** [NBISweden/GenErode#32]
Many of us are now running GenErode with snakemake 7 to avoid issues with Singularity version changes. However, Snakemake has changed their rerun behaviour in Snakemake 7.8 (see https://github.com/snakemake/snakemake/issues/1694). This means that when changing metadata tables for example, snakemake will run everything from the beginning, stating "Set of input files has changed since last execution". To get around this you can use "--rerun-triggers mtime" in the snakemake command. Also applies to any local changes in code or other parameters.

**Comment by verku** [comment]
Thanks for looking into this! I'll make sure to update the documentation accordingly.

**Comment by verku** [comment]
The Wiki is now updated accordingly: https://github.com/NBISweden/GenErode/wiki/2.-Requirements-&-pipeline-configuration#1-prepare-metadata-files-of-samples
