### ISSUE TITLE
Wrong input file in rule index_realigned_bams in workflow 3.1_bam_rmdup_realign_indels.smk?

### ISSUE THREAD

**Issue by johannanvs** [NBISweden/GenErode#44]
Hi,

On line 545 in '3.1_bam_rmdup_realign_indels.smk' you find the rule 'index_realigned_bams', which is designed to index the output bam file from the previous rule 'indel_realigner', as I understood it.

The output bam file from rule 'indel_realigner' is: {sample}.merged.rmdup.merged.realn.bam

The input bam file for rule 'index_realigned_bams' is: {sample}.merged.rmdup.merged.bam
The output bai file from rule 'index_realigned_bams' is: {sample}.merged.rmdup.merged.realn.bam.bai

Am I missing something, or should not the input bam file for rule index_realigned_bams' then be: {sample}.merged.rmdup.merged.realn.bam?

Sincerely,
Johanna

**Comment by verku** [comment]
Yes, you are right! I'll correct it in the upcoming version. Thanks for letting me know!
