### ISSUE TITLE
rule 7_mlrho dependant on final 3.1 bam.bai temporary file

### ISSUE THREAD

**Issue by lored322** [NBISweden/GenErode#48]
Rule 7_mlRho looks for .bam.bai files as input even though it only uses the .bam files. However in both 3.1 and 3.3 bam processing steps, these bam.bai files are marked as temporary and deleted at end of the pipeline run. Thus, if any files are missing from the expected output of 3.1 (i.e. sorted bams), then the pipeline will remap all affected samples from the beginning.

This is different to the 4_genotyping rule, which is only dependant of the final bam file from 3.1/3.2/3.3, and thus the absence of the bam.bai file will not trigger a remapping of any samples. 

One option would be to make the bam.bai files not temporary, or otherwise remove the code calling them in 7_mlRho.smk (which works).

**Comment by verku** [comment]
Thank you for reporting this issue! We will include one of the solutions in the next pipeline version.

**Comment by verku** [comment]
If you can't wait until then, you can solve this by removing the `temp()` flag yourself from the following lines of code:

https://github.com/NBISweden/GenErode/blob/4fc1faad59e0020f915d87e2a8c4e4ff25aa9d35/workflow/rules/3.1_bam_rmdup_realign_indels.smk#L549

https://github.com/NBISweden/GenErode/blob/4fc1faad59e0020f915d87e2a8c4e4ff25aa9d35/workflow/rules/3.3_bam_subsampling.smk#L65
