### ISSUE TITLE
Problems running pipeline in Uppmax using the rhinos test dataset and slurm profile

### ISSUE THREAD

**Issue by apfuentes** [NBISweden/GenErode#50]
Dear GenErode team,

First of all, thank you for developing this great tool.

I have been trying to run the pipeline in Uppmax on the test dataset of rhinos provided in the Wiki and the slurm profile, but it fails. I have examined various things, and even deleted and reinstalled both the pipeline and the condo environment several times, without luck. Thus I wonder if any of you could help me identify the source of the problem to fix it?

Attached, please find a PDF (markdown) summarising the steps followed, as well as the input and output/log files of the pipeline.

Thanks in advance for any help!

Best regards,

Angela

[Troubleshooting_problem_running_test_dataset_GenErode_in_Uppmax.pdf](https://github.com/NBISweden/GenErode/files/12068132/Troubleshooting_problem_running_test_dataset_GenErode_in_Uppmax.pdf)
[help_files.zip](https://github.com/NBISweden/GenErode/files/12068133/help_files.zip)

**Comment by johnne** [comment]
Hi Angela,
As a first step, could you run `conda list > generode.packages.txt` (with your generode environment activated) and upload that txt file with conda package versions here?

**Comment by johnne** [comment]
Can you run (with `generode` environment activated):

```bash
which python
```

and 

```bash
module list
```
